name: Release feature

on:
  push:
    branches:
      - 'feature/**'
      - 'bugfix/**'
  pull_request:
    branches:
      - 'feature/**'
      - 'bugfix/**'

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  ci:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - run: npm install
      - run: npm run lint
      - run: npm run build
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.TIME_MANAGEMENT }}
        run: npx semantic-release